kazzmir/master-of-magic

- .gitignore
- game/magic/city/city.go
- game/magic/game/game.go
- game/magic/main.go
Hi @kazzmir
Great work on the Master of Magic clone!
This PR introduces a small enhancement: it suggests city names from the `cityname.lbx` file when creating a new settlement.
The name suggestions are based on the race of the settlers and whether the name has already been taken:
- Find the next name for a race not already taken.
- If all names for a particular race are already assigned, the next free name from any race is selected.
- If all predefined names are taken, a fallback suggestion of the format "City {number}" is provided.
- In contrast to the description in the [Master of Magic Wiki](https://masterofmagic.fandom.com/wiki/Town#Settlement_Names), no randomization is performed.
It seems that `cityname.lbx` contains an array of fixed-size strings, with both the size and the number …
> city: use predefined city names

- game/magic/game/game.go
- game/magic/main.go
- game/magic/player/player.go
I noticed some things in the overworld fog:
- The sprite for the west edge is wrong
- Using the west edge for east edge is not working
- The inital fog is a bit to small
This is the sprites from the [steam version](https://store.steampowered.com/app/1146370/Master_of_Magic_Classic/):
This is what it looks currently:
This is what the [original](https://playclassic.games/games/4x-dos-games-online/play-master-of-magic-online/play/) looks like:
This is what it looks like with the changes:
Changes made:
- Fix sprite index for west edge
- Load and use sprite for east edge
- Removed commented-out code as this works otherwise very well
- Lower the threshold for lifting the fog by using `radius + 0.5` instead of `radius`
- Adapted the radius for initial city view and unit movement
> overworld: fog fixes

- util/lbxdump/main.go
Allows to use `rawDump` and `indexOnly` options to be used without a zip file.
```bash
./lbxdump --help
Usage: ./lbxdump [options] filename
Options:
-index int
Only the file with the given index (optional) (default -1)
-raw
Dump the files as binary (optional)
-zip string
Path to the zip file (optional)
Example:
./lbxdump --zip data.zip --index 0 --raw
```
> lbxdump: unify arguments

- game/magic/artifact/create-artifact.go
- game/magic/artifact/item.go
Adds autogeneration of artifact names.
Names are generated as in the original game based on the selected powers, for example "+3 Orb of Power". Names change when changing powers and/or (misc) icons. Once a name has been changed manually, autogeneration is disabled.
Names of abilities and spells are not implemented yet.
I also added more `XYZBonus` functions, but I'm not sure if this fits your plans (especially regarding magic ranged attack).
> artifact: add autogenerated names

- game/magic/artifact/create-artifact.go
- game/magic/artifact/item.go
- game/magic/data/abilities.go
- game/magic/game/game.go
- game/magic/game/vault.go
- test/overworld/main.go
- util/lbxdump/main.go
Use power definitions from `itempow.lbx`.
Sorry for the big PR with many changes 😬
Not 100% sure about this. The benefit would be that it also allows to play `Caster of Magic` and others. One drawback might be that there seems to be at least one bug in the original `itempow.lbx` (+6 Defense has actually only +5 Defense) - this makes it impossible to use the definitions from `itempow.lbx` for the items in `itemdata.lbx` (without a workaround).
Changes:
- Read item powers from `itempow.lbx` instead of defining the in the code.
- Use a simple struct for powers (including the name).
- Only store the cost of the whole artifact, not each power. This allows to use the actual costs from `itemdata.lbx` no matter if this matches the sum of costs defined in `itempow.lbx` (not sure if this is a use …
> artfifact: use power definitions from itempow.lbx

- game/magic/game/game.go
- game/magic/game/mercenaries.go
- game/magic/hero/hero.go
- game/magic/units/experience.go
- game/magic/unitview/ui.go
- game/magic/unitview/unit.go
- test/hire-hero/main.go
- test/hire-mercenaries/main.go
- test/overworld/main.go
This PR adds the hire mercanries event:
Event generation is following the description [in the wiki](https://masterofmagic.fandom.com/wiki/Mercenaries):
- does not trigger if
- early in the game
- the player is being banished (no fortress city)
- generates the event with a chance of `max(10, 1 + fame / 20)`%
- selects a random unit from all units except
- fantastic or hero
- settlers
- ships
- races from an absent plane
- select a random number of units between 1 and 3
- selects random experience points of 20 (level 1) / 60 (level2) / 120 (level 3)
- costs `#units * production cost * (level + 3) / 2 [* 0.5 if charismatic]`
- puts the units in the fortress city if hired
Random unit selection is done slighty different: It first selects a list of possible candidates to choose from instead of …
> Add hire mercenaries event

- game/magic/artifact/item.go
- game/magic/artifact/view.go
- game/magic/artifactview/view.go
- game/magic/game/game.go
- game/magic/game/merchant.go
- game/magic/game/vault.go
- game/magic/unitview/unit.go
- test/merchant/main.go
- test/overworld/main.go
Adds the merchant event:
All predefined items are read from the `itemdata.lbx` and added to a pool, where they can be taken out by the merchant (or later for lair treasure).
Also adds requirements (number of books in certain magic types) to artifacts and reads them for the predefined items from `itemdata.lbx`
Event generations follows the description in the [wiki](https://masterofmagic.fandom.com/wiki/Merchant):
- generates the event with a chances of `max(10, 2 + player.Fame / 25 [*2 if famous])`
- cost is `artifactCost [/ 2 if charismatic]`
- an item is skipped, if the requirements are not met (the merchant has 12 books in every type of magic)
I further moved the part of drawing an artifact also used in the vault to a new `artifactview` folder.
@kazzmir What do you think?
> Add merchant event

- TODO
- game/magic/shaders/edge-glow.kage
Just a small bug in the edge glow shader.
Before:
After:
> shader: fix edge glow shader corner evaluation

- TODO
- game/magic/game/game.go
- game/magic/game/hero.go
- game/magic/hero/hero.go
- game/magic/hero/hero_test.go
- game/magic/unitview/unit.go
- test/overworld/main.go
Adds the hero level up popup:
The overworld scenario 26 contains two heros:
- Gunther will gain the next level at the start of the turn
- Raywind will gain the next level if combat against the spearman is won
Does not render the ability improvements (they seem not to be implemented yet).
> Add hero level up message

- TODO
- game/magic/camera/camera.go
- game/magic/combat/combat-screen.go
- game/magic/game/cast.go
- game/magic/game/game.go
- game/magic/game/surveyor.go
- game/magic/inputmanager/input.go
- game/magic/main.go
- game/magic/maplib/map.go
- game/magic/maplib/map_test.go
- game/magic/util/image-cache.go
- test/cityview/main.go
- test/overworld/main.go
Allow the overworld to be zoomed in/out so the user can see more of the map. Moving between coordinates on the map is also done smoothly.
> overland: zoom in/out using mouse wheel/trackpad

- game/magic/combat/model.go
- game/magic/game/game.go
- game/magic/pathfinding/path.go
- game/magic/pathfinding/path_test.go
- test/overworld/main.go
If the map is 50 tiles long then (49,0) should be 1 unit away from (0,0), so pathfinding has to take into account the fact that (50,0) is the same as (0,0).
> pathfinding: take map wrapping into account

- game/magic/game/game.go
- game/magic/player/player.go
- game/magic/player/stack.go
Show a G icon in the UI for a stack of units that are moving.
Also allow to change the path of a unit that has already exhausted its moves.
> units: allow user to modify path after movement, add G icon

- game/magic/game/game.go
- game/magic/maplib/map.go
- test/overworld/main.go
1. limit drawing the overworld to a subimage of the screen so that icons/tiles don't accidentally get drawn onto the UI part
2. ignore pathfinding through lair/caves, and also set a lair/cave to empty if the monsters are defeated
> Limit movement icon

- game/magic/game/game.go
- game/magic/terrain/map.go
- game/magic/terrain/terrain.go
Make the random terrain placement a bit less arbitrary looking by:
- placing tundra only near the poles
- placing desert only near the center
- use some weights
- generate a bit less land in general
- generate a bit less land at the poles
> map: make random terrain placement appear less arbitrary

- game/magic/artifact/create-artifact.go
- game/magic/game/game.go
- test/artifact/main.go
The create artifact screen should take the runemaster retort into account when showing the cost to the user. This fixes #207.
The test/artifact program allows you to toggle artificer and runemaster using the f1/f2 keys.
> create artifact: pass in runemaster retort for cost adjustment

- game/magic/combat/combat-screen.go
- game/magic/combat/model.go
- game/magic/game/game.go
- game/magic/hero/hero.go
- game/magic/spellbook/spell.go
- game/magic/units/overworld.go
- game/magic/units/stack-unit.go
- test/cast-spell/main.go
- test/combat/main.go
If a hero is granted spells via a spell charge power on an item then the casting that spell should first use up a charge before using any mana that hero may have.
> combat: handle casting spells using charge powers

- TODO
- game/magic/artifact/create-artifact.go
- game/magic/artifact/item.go
- game/magic/combat/combat-screen.go
- game/magic/combat/model.go
- game/magic/game/game.go
- game/magic/game/treasure.go
- game/magic/hero/hero.go
- game/magic/maplib/map.go
- game/magic/maplib/node.go
- game/magic/player/player.go
- game/magic/setup/new-wizard.go
- test/overworld/main.go
create treasure loosely based on the logic described in https://masterofmagic.fandom.com/wiki/Treasure
This logic is a bit simpler. Given a budget (which normally comes directly from the encounter itself), a random treasure type is selected if it will fit in the budget, and that type of treasure is added to the overall list of treasure items. Then the budget is decreased by an amount related to the selected treasure item, and another treasure type is selected at random.
> encounter: give treasure when the node is defeated

- game/magic/setup/new-game.go
- game/magic/setup/new-wizard.go
Icrease the contrast for the font's used in the start game screens for better readability.
Before:
After:
For Reference: This is the original game:
Also fixes button positions.
Before:
After:
> new-game: increase contrast

- game/magic/game/cast.go
- game/magic/game/game.go
- game/magic/maplib/map.go
- test/overworld/main.go
Implement [Raise Volcano](https://masterofmagic.fandom.com/wiki/Raise_Volcano) Spell.
Volcanoes:
- may be cast on desert, forest, swamp, frass, and tundra
- destroys any bonus
- may destroy buildings with a chance of 15%
- generate 1 power for the casting wizard
- have a chance of 2% of reverting back to mountain, and thereby a chance of 5% of generating a random mineral
- can be reverted also with change terrain
I also reused the `Melder` interace but renamed it to `Wizard`, not sure if that is a good idea.
I also refactored the spells that affect the map. They now all behave the same way: for example centering on the tile and resetting zoom. The common/duplicated code is now in `doCastOnMap`. Since some things need to happen mid-animation (for example changing terrain when the animation …
> cast: implement raise volcano

- game/magic/city/city.go
- game/magic/data/data.go
- game/magic/game/surveyor.go
- game/magic/maplib/map.go
Rely (only) on the `BonusType` definitions in `city`, `maplib` and `surveyor`.
I think there is also a small bug: coal and iron currently provide a general production bonus instead of only bonus to producting new units. I would leave this as a FIXME for now.
> data: unify usage of BonusType

- game/magic/city/city.go
- game/magic/game/game.go
- game/magic/game/surveyor.go
- game/magic/maplib/map.go
- game/magic/terrain/terrain.go
Rely (only) on `FoodBonus`, `GoldBonus` and `ProductionBonus` of a tile.
Since some of these Bonuses rely on neighboring tiles in case of River Mouths, I've moved these definitions from `terrain` to `map`. This will also be needed when disabling the bonuses in case of corruption.
I've also moved the gold bonus logic previously in `city` to `GoldBonus` together with `IsRiverMouth` and `IsTouchingShore`. This also allows the surveyor to display the gold bonus and river shores.
TBH, the wiki is very confusing (maybe sometimes contradicting) regarding these bonuses and the original surveyor seems to report many errors. Although this implementation might be more correct, most of the informations of the surveyor per se are actually not useful as it's not clear how the bonuses apply (e.g. gold …
> map: unify usage of terrain tile bonuses

- game/magic/game/game.go
- game/magic/game/treasure.go
Treasure can contain a spellbook count of 1 or 2, or 1/2 retorts. Also fix positioning of the treasure popup
> treasure: give 1 or 2 spellbooks/retorts

- game/magic/spellbook/data.go
... I didn't realize sorting by name wasn't even necessary as `MagicType` is an `int` anyway.
> spellbook: simplify sorting

- game/magic/game/game.go
- game/magic/maplib/map.go
- game/magic/maplib/node.go
- game/magic/ui/dialogs.go
- test/overworld/main.go
Use `ExtraEncounter` for all kinds of enemy encounters including the (initial) enemies on nodes.
Once an encounter is won, it will be removed from the map. Nodes initially have both an `ExtraEncounter` and an `ExtraMagicNode`, but the first player to win removes the encounter.
This will remove some code code duplication and makes some parts easier (for example path finding will never cross an encounter; removes `IsEmpty` as it isn't needed anymore).
It will also allow to add a set of players already explored an encounter centrally to `ExtraEncounter`.
> map: refactor nodes and encounters

- game/magic/game/game.go
- game/magic/game/surveyor.go
- game/magic/maplib/map.go
- game/magic/maplib/node.go
Adds exploration: Once an encounter has been started (and not entered or fled), the (first) enemy type is shown in the surveyor.
Also makes the surveyor output more like the original: show nodes as a terrain + special, move city margin message further down.
> Exploration

- game/magic/terrain/map.go
- game/magic/terrain/map_test.go
- game/magic/terrain/terrain.go
- game/magic/terrain/terrain_test.go
- util/mapeditor/main.go
master:
```
map.go:661: Generated 200x150 Arcanus map in 324.832612ms
```
this pr:
```
map.go:670: Generated 200x150 Arcanus map in 124.716458ms
```
I applied the following optimizations, sorted from biggest gain to smallest gain:
1. Store a map from TerrainType to []TerrainTile in the TerrainData object. This means that for FindMatchingTile(), if the match map has a Center direction then it only has to consider tiles of that type, so this can avoid iterating through every single tile.
2. Instead of calling map_.Copy() in placeRivers ::resolves() each time instead a single map copy is made in placeRivers, and resolves() just copies all the values from the original map to the copied map using the builtin copy() function.
3. The DirectedCompatibility and Compatibilty structs have a …
> map: optimize land generation

- game/magic/combat/end-screen.go
- game/magic/game/game.go
- game/magic/maplib/node.go
- game/magic/player/player.go
- game/magic/units/unit.go
- test/overworld/main.go
Adds some [sources for fame](https://masterofmagic.fandom.com/wiki/Fame#Sources_for_Fame):
- from Famous ability
- from battle
- ±1 for 4+ enemies
- ±1 for fantastic creatures with spell cost ≥ 600 MP. I moved the costs from `nodes` to `units` and added the missing costs (based on the [wiki](https://masterofmagic.fandom.com/wiki/Fantastic_Unit#List_of_Summoned_Units)). Theoretically, these costs could differ in the `spelldat.lbx` but I don't think it make much sense to adjust these when loading the lbx, right?
- -1 for every two hero levels of a dead hero (starting from Myrmidon)
The following are still missing:
- from razing cities (added fixmes)
- from just cause spell (added a fixme)
- from defeated enemy wizard (that's not implemented yet, right?)
The gained / lost fame is now …
> game: add some sources for fame

- game/magic/ai/raider.go
- game/magic/armyview/view.go
- game/magic/city/city.go
- game/magic/data/data.go
- game/magic/game/cast.go
- game/magic/game/game.go
- game/magic/game/surveyor.go
- game/magic/hero/hero.go
- game/magic/main.go
- game/magic/maplib/map.go
- game/magic/player/player.go
- game/magic/player/stack.go
- game/magic/units/overworld.go
- game/magic/units/stack-unit.go
- game/magic/units/unit.go
- game/magic/util/graphics.go
- test/combat/main.go
- util/combat-simulator/main.go
Implements range of sight of units/cities and fog of war for units (but not terrain, cities etc.)
The fog map of a player can now have 3 values:
- unexplored: player has never seen the tile
- explored: player has once seen the tile
- visible: the tile is currently visible by a unit or city of a player
The wiki is very unclear about this topic. What I've found out from testing with the original and the wiki:
- Fog of war (explored tiles) hides enemy units
- Cities have a range of sight
- normal cities have 2 square
- cities with oracle have 4 square
- cities with Nature's Eye spell have 5 square
- Units have a range of sight
- normal units have 1 square
- flying units have 2 square
- units with scouting have 2 or 3 square (there seems to be no Scouting I, only II and III see …
> game: implement range of sight

- game/magic/terrain/terrain.go
myrror maps were getting arcanus tiles
> terrain: check plane when matching tiles

- game/magic/city/city.go
- game/magic/cityview/city-screen.go
- game/magic/data/enchantment.go
- game/magic/game/cast.go
- test/cityview/main.go
- test/overworld/main.go
Adds nature's eye spell.
The drawing order is like in the original: City walls, enchantment icon(s), magic walls. Due to the sorting by name this should also work for the other icons (prosperity etc.).
> cast: implement nature's eye spell

- game/magic/cityview/city-screen.go
When a building is sold, recreate the UI to show the updated resource icons in case the building affected resources (such as granary adding +2 food).
Also don't show more subsistence farmers than the number of actual farmers.
> city: fix some issues with food icons/workers

- game/magic/cityview/city-screen.go
- game/magic/cityview/enchantment.go
- game/magic/data/enchantment.go
- test/cityview/main.go
Adds the sprite indexes for myrror cities:
Also renders enchantments changing the background of the city (for both planes; in the order of precedence):
- flying fortress
- famine
- cursed lands
- gaias blessing
Or the horizon (for both planes; in the order of precedence):
- Chaos rift
- Heavily Light
- Cloud of Shadow
I also added some fixme's (where I'm quite sure but not 100%):
- hills and moutain horizon seem to depend on the tiles north of the city
- besides river there is also shore (I think an any sourrounding tile)
`test/cityview` allows to now to toggle plane (`p`-key) and the enchantments mentioned above (keys `1`-`7`).
> cityview: fix myrror city display

- game/magic/city/city.go
- game/magic/city/city_test.go
- game/magic/cityview/city-screen.go
- game/magic/game/game.go
- test/cityview/main.go
I added a test for enchantment combinations and started testing city calculations against cities in Dos MoM and noticed some differences.
The following have been fixed:
- Granary has [+2 influence](https://masterofmagic.fandom.com/wiki/Granary) on maximum population instead of +1
- Production from farmers should be [rounded up](https://masterofmagic.fandom.com/wiki/Production#Base_Production)
- Add influcence of buildn [housing](https://masterofmagic.fandom.com/wiki/Housing) on population growth
- The influence of gaia's blessing is reported differently across the wiki, I changed so that it get's accounted for in [`BaseFoodLevel`](https://masterofmagic.fandom.com/wiki/Food#Base_Food_Level) and [excluded Wild Game](https://masterofmagic.fandom.com/wiki/Maximum_Population#Wild_Game)
The …
> city: various fixes

- game/magic/city/city.go
- game/magic/city/city_test.go
- game/magic/data/enchantment.go
- game/magic/game/cast.go
- game/magic/game/game.go
- test/cityview/main.go
- test/overworld/main.go
Adds [pestilence](https://masterofmagic.fandom.com/wiki/Pestilence) spell and enchantment.
Pestilence:
1. Adds +2 unrest
2. Removes 1000 population if a city contains 11 or more citizen
3. Randomly removes 1000 population if a city contains 10 or less citizen with a chance of `citizens > rand.IntN(10) + 1`
Pestilence seems to have no visual indication in the city screen and the original dos mom only shows the city screen when casting, so I done that.
(The wiki talks of 9 or less citizen for the third effect but that would create a stop a 10 citizens which the the original game clearly does not have.)
> cast: add pestilence

- game/magic/city/city.go
- game/magic/game/game.go
- test/overworld/main.go
I tested with Dos MoM (v 1.60) and it's actually possible to shrink a city to zero by building / buying a settler.
Dos MoM doesn't show any notification, but I think it might be better to show something similar to the deserted outpost, what dou you think?
I also moved city capping and growth message generation below the unit production part because building settler will also influence the population.
> city: remove city if shrunk to zero

- game/magic/cityview/city-screen.go
- game/magic/ui/dialogs.go
- test/cityview/main.go
- test/overworld/main.go
https://masterofmagic.fandom.com/wiki/Town#Buying_Production
> city: implement buy button

- game/magic/building/building.go
- game/magic/city/city.go
- game/magic/cityview/city-screen.go
- game/magic/game/game.go
- test/cityview/main.go
Dos MoM doesn't render some of the buildings and shows them as "Replaced" in the resource dialog.
This will free up some city slots. I think at some point it might be required to switch to a more fine-grained grid layout similar to what Dos MoM does, as the building slots will still run out quickly for bigger cities. I've added some screen shots for reference #306.
> cityview: don't render replaced buildings

- game/magic/combat/combat-screen.go
- game/magic/game/cast.go
- game/magic/maplib/node.go
- game/magic/summon/summon.go
- game/magic/units/unit.go
- test/overworld/main.go
Floating island is actually not summoned to the summoning circle but cast on a map tile with water (including lakes).
Also includes some smaller fixes regarding summoning:
- only show combat spells in the spellbook during combat
- fixes summoning picture of some units: shadow demons, death knights, cockatrices, giant spiders
So far, only "Lycantrophy" is missing of all the summoning spells! Not sure how this is rendered though...
Maybe better add some helper function to look up a stack on map?
> cast: fix floating island summoning

- game/magic/cityview/city-screen.go
- game/magic/ui/ui.go
In the city view if there are too many enchantments then the enchantment names could overflow the window. This pr prevents the enchantments list from getting too long and providing up/down arrows to scroll the list. Scrolling via mouse wheel/trackpad is also supported
> city view: handle enchantment overflow

- game/magic/game/cast.go
- game/magic/game/game.go
- game/magic/game/hero.go
- game/magic/hero/hero.go
- game/magic/player/player.go
- test/overworld/main.go
Implements the "Incarnation" spell:
Also fixes some small issues:
- `GameEventVault` missing player variable
- deceased heros keeping equipment (Torin can be incarnated again, other heros resurrected)
- level of hired heros getting reset when being hired (heros will level up when not being hired, torin keeps his level on re-summoning)
> cast: add incarnation

- game/magic/city/city.go
- game/magic/city/city_test.go
- game/magic/cityview/city-screen.go
- game/magic/data/enchantment.go
- game/magic/game/cast.go
- game/magic/game/game.go
- test/cityview/main.go
- test/overworld/main.go
I don't really like game/magic/game/cast.go lines 113 - 120. Maybe there's a new func (something like RemoveAllCityEnchantmentsOfTypes()) needed? The current RemoveCityEnchantment requires providing the spell's owner, which is not the case with Consecration.
I also don't really like 6868-6880 in game.go. I think we need a func like useMap.performFuncForEachCityCatchmentTile() with city and func (tileX, tilyY int) as arguments?
Also, I've added chaos/death wards checks for the spells affected by Consecration-related changes, except for some cases where there already was one.
> Overworld: implement Consecration

- game/magic/game/game.go
- game/magic/setup/new-wizard.go
I'm not sure you'll accept this...
Well. In the original MOM any LMB or RMB click closes text inputs as if "enter" was pressed. Currently, in this project only enter keyboard key closes text inputs.
I've made it similar to OG MOM (it seems reasonable, as it allows mouse-only play), but still with some differences:
1. RMB does nothing (it can be used for something else)
2. LMB on the text input itself does nothing (we would use it for moving the cursor?)
3. Artifact creation menu unchanged. Not sure this behavior is needed here at all
> Make LMB enter the text input.

- game/magic/game/cast.go
- game/magic/game/game.go
- game/magic/maplib/map.go
- test/overworld/main.go
Dispel warp node if the warp node was cast by a rival wizard. This also tracks the original caster of warp node in the ExtraMagicNode object
> disenchant area: apply to warp node

- game/magic/game/cast.go
All the spells are split into the following categories (as in the wiki):
-     Summoning Spells
-     Unit Enchantments
-     Unit Curses
-     Town Enchantments
-     Town Curses
-     Global Enchantments
-     Instant Spells
-     Combat Enchantments
-     Combat Instants
All TODOs are moved to their respective delimiter comments.
> Reorder and categorize spells.

- game/magic/city/city.go
- game/magic/city/city_test.go
- game/magic/cityview/build-screen.go
- game/magic/game/game.go
- game/magic/game/game_test.go
- game/magic/main.go
- game/magic/player/player.go
- test/city-enchantment/main.go
- test/cityview/main.go
- test/combat/main.go
- test/overworld/main.go
- test/scale/main.go
Now that a city has a reference to a reign provider, some attributes can be moved to there... what do you think?
> city: move attributes from player to reign provider

- game/magic/ai/enemy.go
- game/magic/city/city.go
- game/magic/city/city_test.go
- game/magic/cityview/city-screen.go
- game/magic/game/cast.go
- game/magic/game/game.go
- game/magic/game/game_test.go
- game/magic/magicview/view.go
- game/magic/main.go
- game/magic/player/player.go
- test/city-enchantment/main.go
- test/cityview/main.go
- test/overworld/main.go
- test/scale/main.go
Update unrest when adding and/or removing city and/or global enchantments.
I also added (the already existing) `GetUnits` to `ReignProvider` so cities can query their garrison themselves.
@kazzmir What do you think? Anything I missed?
> city: update unrest on enchantment changes

- game/magic/city/city.go
- game/magic/city/city_test.go
- game/magic/game/cast.go
- game/magic/game/game.go
- game/magic/game/game_test.go
- test/city-enchantment/main.go
- test/cityview/main.go
- test/overworld/main.go
Armageddon and Great Wasting also adds unrest. I went with the [Code from 1.31](https://github.com/jbalcomb/ReMoM/blob/main/src/CITYCALC.C#L3282) + the indicated fixes:
- Armageddon adds +2 unrest per enemy enchantment
- Great Wasting adds +1 unrest per enemy enchtantment
I also add protection by Consecration and Chaos Ward for the city centers.
What do you think, does that make sense @kazzmir @sidav?
> cast: add unrest from Armageddon and Great Wasting

- game/magic/spellbook/spell.go
round the amount so that it can go upto the maximum. Without this pr the maximum mana was always 1 less than the true max
> cast: round additional power to fix off-by-1

- game/magic/city/city.go
- game/magic/city/city_test.go
- game/magic/cityview/city-screen.go
- game/magic/game/game_test.go
- game/magic/maplib/map.go
- test/combat/main.go
Resolves some todos regarding rivers and coasts in cities:
- draws shore in city scape if nearby shore
- draws river in city scape if nearby or on top of river
- include gold bonus in city gold calculation (use the same as the surveyor already does)
- fix river mouths considering edge shore tiles
> city: handle river/coast gold bonus

- game/magic/artifact/item.go
- game/magic/hero/hero.go
- game/magic/units/overworld.go
- test/overworld/main.go
an item with Haste should provide the hero with the Haste enchantment, and apply the haste bonus to the movement points.
> hero: include enchantments from artifacts. fix overworld move speed

- game/magic/cityview/city-screen.go
- game/magic/data/enchantment.go
- game/magic/game/cast.go
- game/magic/game/game.go
- game/magic/hero/hero.go
- game/magic/units/overworld.go
- game/magic/units/stack-unit.go
- test/overworld/main.go
Lycanthropy
- keeps weapon bonus
- keeps damage
- resets experience
- cannot be cast on fantastic units, heroes or undead / black or chaos channeled units and will generate an error message while allowing to select another unit
I also
- added notices when trying to cast a unit or city enchantments on a unit / city which already contains the enchantment (it allows to select another unit / city)
- made black channeled units (irreversibly) undead
- changed showing a notice always playing the beep
For this PR, I have done some refactoring, mostly to allow the notices and to remove some code duplication:
- move `selected` to `doCastCityEnchantments` similar to `doCastUnitEnchantment`
- added `before` and `after` callbacks to `doCastCityEnchantments`
- added `before` and `after` callbacks to …
> cast: add lycanthropy

- util/fonteditor/main.go
1. ctrl-z undos last color change
2. show alpha sprite in palette
3. h values are from 0-360 to match gimp
the checkerboard pattern indicates alpha=0
> fonteditor: add undo, alpha sprite

- game/magic/city/city.go
- game/magic/city/city_test.go
- game/magic/cityview/city-screen.go
- test/cityview/main.go
negative net gold from a city makes the surplus icons show up in grey scale
> city: surplus gold can be negative

- game/magic/combat/combat-screen.go
- game/magic/combat/model.go
- game/magic/game/cast.go
- game/magic/game/game.go
- test/combat/main.go
- test/overworld/main.go
Adds the [Eternal Night](https://masterofmagic.fandom.com/wiki/Eternal_Night) global enchantment, which adds Darkness to battles if not already under the influence of Cloud of Shadow.
Not 100% sure what the wiki means with "protected" here:  "every battle that does not take place in a Town protected by Heavenly Light comes under an effect virtually identical to that of the Darkness spell". Since True Light negates Darkness and Eternal Night just adds Darkness I guess we should just add it and let Heavenly Light "protect" by negating the effects.
I also added a check to `AddEnchantment` since DOS MoM does not allow casting Darkness/True Light if is already preset as global enchantment.
> cast: add eternal night

- game/magic/load/load.go
- util/mapeditor/main.go
Keep two separate planes in the map editor; load both from the savegame.
I have leftover data with my savegames, maybe this is due to the community patch storing more data? the terrain data at least seems to be ok....
> mapeditor: use two planes

- game/magic/combat/combat-screen.go
- game/magic/combat/combat_test.go
- game/magic/combat/model.go
- game/magic/combat/spell_test.go
- game/magic/game/cast.go
- game/magic/game/game.go
- game/magic/hero/hero.go
- game/magic/player/player.go
- game/magic/units/overworld.go
- game/magic/units/stack-unit.go
- test/combat/main.go
1. add heroism combat spell
2. track damage to a unit rather than its health, so that if the health of the unit increases the damage does not change
3. every unit has a reference to its containing ArmyUnit during combat that must be removed when combat ends via unit.SetEnchantmentProvider(nil)
> add heroism projectile

- game/magic/combat/combat-screen.go
- game/magic/combat/model.go
- game/magic/data/enchantment.go
- game/magic/game/cast.go
- game/magic/game/game.go
- game/magic/player/player.go
- test/overworld/main.go
Adds [Word of Recall](https://masterofmagic.fandom.com/wiki/Word_of_Recall) and [Recall Hero](https://masterofmagic.fandom.com/wiki/Recall_Hero) spells.
Also adds some bit of code to relocate units in case the stack at the summoning circle is full. The same logic is used when summoning units or producing units. I'm not 100% sure but I think original moved a random unit so I did that.
I'm not sure what happens if there is no room to move existing units so I added some logic to sort units by some sort of "value" (for example heros are sacrified last).
I also refactored the existing flee function to reuse the common parts.
> cast: add recall hero and word of recall

- game/magic/artifact/create-artifact.go
- game/magic/artifact/item.go
- game/magic/combat/combat-screen.go
- game/magic/game/cast.go
- game/magic/game/game.go
- game/magic/game/learn-spell.go
- game/magic/player/player.go
- game/magic/player/player_test.go
- game/magic/setup/new-wizard.go
- game/magic/spellbook/data.go
- game/magic/spellbook/spell.go
- game/magic/spellbook/spell_test.go
- test/artifact/main.go
- test/cast-spell/main.go
- test/combat/main.go
- test/overworld/main.go
* compute the cost of a spell while taking all retorts and spell book modifiers into account, as well as the evil omens global enchantment
* compute extra research progress for some types of spells, also based on retorts/spell books
* fix a bug in the new wizard custom books ui where a retort can be selected without the proper number/type of spell books
* remove artificer/runemaster from create artifact, and just let the final spell cost be computed the same as every other spell
> cast evil omens

- game/magic/armyview/view.go
- game/magic/artifact/create-artifact.go
- game/magic/citylistview/view.go
- game/magic/cityview/build-screen.go
- game/magic/cityview/city-screen.go
- game/magic/combat/combat-screen.go
- game/magic/combat/end-screen.go
- game/magic/combat/unit-view.go
- game/magic/diplomacy/diplomacy.go
- game/magic/game/cast.go
- game/magic/game/game.go
- game/magic/game/hero.go
- game/magic/game/mercenaries.go
- game/magic/game/surveyor.go
- game/magic/game/vault.go
- game/magic/magicview/view.go
- game/magic/mainview/view.go
- game/magic/setup/new-game.go
- game/magic/setup/new-wizard.go
- game/magic/spellbook/spell.go
- game/magic/ui/ui.go
- game/magic/unitview/ui.go
- game/magic/unitview/unit.go
- test/hire-hero/main.go
- test/hire-mercenaries/main.go
Show a tooltip for some ui elements, so far just the unit stats.
since counting the icons is annoying
> ui: add tooltip to unit stats

- game/arena/cost.go
- game/arena/main.go
- game/arena/player/player.go
buying mana costs more for each successive mana point, but persists after each battle
> arena: make mana permanent, but restore each round

- game/magic/combat/ai.go
- game/magic/combat/combat-screen.go
- game/magic/combat/model.go
Hold down CONTROL while selecting a tile to move towards in order to allow the unit to walk along a path to the tile even if the unit cannot move along the entire path in a single turn.
> combat: move towards tile

- game/magic/combat/combat-screen.go
- game/magic/combat/combat_test.go
- game/magic/combat/model.go
- game/magic/combat/observer.go
- game/magic/game/damage_test.go
- game/magic/game/game.go
Each figure in an attacking unit does a separate attack roll that can individually be blocked.
> combat: fix multi-unit attack rolls
