kazzmir/master-of-magic

util/lbxviewer/main.go

show all tiles, and choose one to display by pressing enter

Lbxviewer tiles

---

game/magic/setup/new-wizard.go
test/new-screen/main.go
test/new-wizard/main.go

test facility for running the new game screen

New screen test

---

game/magic/city/city-screen.go
game/magic/city/city.go
game/magic/setup/new-wizard.go
game/magic/ui/ui.go
util/fontviewer/main.go

show the name of the building as the user hovers over it. left click sells the building and right click shows a help dialog box

City view names

---

game/magic/cityview/build-screen.go
game/magic/cityview/city-screen.go
game/magic/game/game.go
game/magic/magicview/view.go
game/magic/setup/new-game.go
game/magic/setup/new-wizard.go
game/magic/ui/dialogs.go
game/magic/units/abilities.go
lib/font/font.go
lib/font/read.go
lib/lbx/font.go
lib/lbx/lbx.go
util/fontviewer/main.go
util/lbxdump/main.go

move font reading code to the lib/font module instead of lib/lbx. add a convenience function for reading one font instead of all of the fonts

Font update

---

game/magic/util/image-cache.go
lib/lbx/lbx.go
util/lbxviewer/main.go

force some lbx entries to use a specific palette

Force palette

---

.github/workflows/build-macos-m1.yml

add macos workflow

---

README.md

show macos badge

---

game/magic/audio/audio.go
game/magic/intro/intro.go
go.mod
go.sum
lib/voc/BlockType.go
lib/voc/Load.go
test/intro/intro.go
util/vocdump/main.go

play the voice audio sounds during the intro

Intro audio

---

docs/assets
game/magic/audio/audio.go
game/magic/combat/combat-screen.go
game/magic/units/unit.go
lib/colorconv/colorconv.go
test/combat/main.go
util/lbxviewer/main.go

Combat screen

---

game/magic/main.go
lib/lbx/cache.go

load data files from drag and dropped files onto the main window

read data from dropped files

---

lib/mouse/mouse.go
util/mouse/main.go

load mouse images out of fonts.lbx

Mouse viewer

---

game/magic/combat/combat-screen.go
game/magic/pathfinding/path.go
game/magic/pathfinding/path_test.go
test/combat/main.go

Combat path

---

game/magic/combat/combat-screen.go
game/magic/combat/combat.go
game/magic/units/unit.go
test/combat/main.go

attacker and defender hit each other based on the melee power and defense values. combat ends when one side runs out of units

start to implement melee damage

---

game/magic/combat/combat-screen.go
test/combat/main.go

show win/lose dialog when combat ends

implement end screen

---

game/magic/game/game.go
game/magic/main.go
test/overworld/main.go

connect overworld movement to combat

Overworld combat

---

game/magic/combat/combat-screen.go
game/magic/game/game.go
game/magic/player/player.go
game/magic/units/unit.go
test/cityview/main.go
test/overworld/main.go

implement unit stacks in the overworld so that groups of units can move in a single step

Overworld stack

---

game/magic/game/game.go

run the magic view screen in its own local function via a coroutine. use a channel to signal from the ui to the main update method

Magic view

---

game/magic/building/building.go
game/magic/city/city.go
game/magic/cityview/city-screen.go
game/magic/game/events.go
game/magic/game/game.go
game/magic/game/testevents/main.go
game/magic/mainview/view.go
game/magic/ui/ui.go
game/magic/util/graphics.go
lib/lbx/lbx.go
test/overworld/main.go

show popup when a new building is created

City new building

---

TODO
game/magic/combat/combat-screen.go
game/magic/data/data.go
game/magic/game/game.go
game/magic/game/map.go
game/magic/main.go
game/magic/setup/new-game.go
game/magic/terrain/terrain.go
game/magic/ui/dialogs.go
game/magic/units/unit.go
game/magic/util/graphics.go
game/magic/util/image-cache.go
game/magic/util/slices.go
game/magic/util/slices_test.go
lib/lbx/lbx.go
test/overworld/main.go
util/lbxviewer/main.go

add guardians to magic nodes. engage combat when units walk onto magic node

Node combat

---

game/magic/combat/combat-screen.go
game/magic/units/overworld.go
game/magic/util/graphics.go
test/combat/main.go

https://golangprojectstructure.com/how-to-make-go-structs-more-efficient/
```
~/go/bin/fieldalignment  ./game/magic/...
```

Optimize structs

---

README.md
game/magic/game/game.go
game/magic/units/unit.go
game/magic/unitview/ui.go
test/overworld/main.go

Small unit view

---

game/magic/building/info.go
game/magic/city/city.go
game/magic/city/city_test.go
game/magic/cityview/city-screen.go
game/magic/data/data.go
game/magic/game/game.go
game/magic/game/map.go
game/magic/game/surveyor.go
game/magic/main.go
game/magic/player/player.go
test/cityview/main.go
test/combat/main.go
test/overworld/main.go

show producers and consumers of resources in city view

---

TODO
game/magic/armyview/view.go
game/magic/cityview/build-screen.go
game/magic/cityview/city-screen.go
game/magic/combat/combat-screen.go
game/magic/combat/combat.go
game/magic/data/enchantment.go
game/magic/game/game.go
game/magic/hero/hero.go
game/magic/shaders/edge-glow.kage
game/magic/shaders/shaders.go
game/magic/units/overworld.go
game/magic/units/stack-unit.go
game/magic/unitview/ui.go
game/magic/unitview/unit.go
game/magic/util/graphics.go
game/magic/util/image-cache.go
game/magic/util/slices.go
test/combat/main.go
test/glow/main.go
test/overworld/main.go

unit glowing effect

---

TODO
game/magic/ai/enemy.go
game/magic/data/data.go
game/magic/diplomacy/diplomacy.go
game/magic/draw/draw.go
game/magic/game/game.go
game/magic/magicview/view.go
game/magic/mirror/mirror.go
game/magic/player/player.go
game/magic/setup/new-wizard.go
game/magic/ui/ui.go
lib/lbx/lbx.go
test/diplomacy/main.go
test/magicview/main.go
test/overworld/main.go

also start a basic diplomacy screen

start to handle ai controlled wizards

---

util/combat-simulator/main.go
util/combat-simulator/server/Makefile
util/combat-simulator/server/go.mod
util/combat-simulator/server/go.sum
util/combat-simulator/server/magic.service
util/combat-simulator/server/server.go

send a bug report from the ui to a server running on a cloud datacenter

combat simulator: send bug report ui

---

util/combat-simulator/main.go

support save/load of the combat configuration

Combat simulator save

---

.gitignore
game/magic/city/city.go
game/magic/game/game.go
game/magic/game/game_test.go
game/magic/main.go

* city: use predefined city names
* Adjust city name fallback

city: use predefined city names (#153)

---

game/magic/game/game.go

Adds the little fog corners.
Before:
After:

overworld: add fog corners

---

game/magic/game/game.go

fix fog color

---

game/magic/city/city.go
game/magic/cityview/city-screen.go
game/magic/data/enchantment.go
game/magic/game/game.go
test/cityview/main.go
test/combat/main.go
test/overworld/main.go

show enchantments on the city in the color of the banner of the casting wizard

city view: show enchantments

---

game/magic/cityview/city-screen.go
game/magic/cityview/enchantment.go
game/magic/game/cast.go
game/magic/util/graphics.go
test/city-enchantment/main.go
test/overworld/main.go

show a view of the city when a new enchantment is cast

City enchantment cast

---

util/lbxviewer/main.go

make lbxviewer use entire window to render tiles

expand view to full size of window

---

util/lbxviewer/main.go

allow the cache to get large, but remove entries that haven't been accessed in a while

Lbxviewer cache

---

game/magic/combat/combat-screen.go

draw a health bar in the ui section

Combat health

---

util/mapeditor/main.go

Mapeditor improvements

---

game/magic/game/game.go

Use some border so that cities have at least two rows of tiles on both sides

Fix city placement

---

game/magic/game/game.go
game/magic/hero/hero.go
game/magic/player/stack.go
game/magic/units/overworld.go
game/magic/units/stack-unit.go
test/overworld/main.go

attempt to handle the case where two stacks are following a path and happen to be on the same tile, but have not merged into a single stack.

show all stacks at the given location in the ui

---

game/magic/game/game.go

make the boot icons show with a highlight

Movement glow

---

TODO
game/magic/cityview/city-screen.go
game/magic/game/cast.go
game/magic/game/game.go
game/magic/main.go
game/magic/maplib/map.go
game/magic/maplib/node.go
game/magic/player/player.go
test/overworld/main.go

implement roads, and how they impact movement in the overworld

use terrain cost in path finding. consider friendly city in cost

---

game/magic/terrain/map_test.go
game/magic/terrain/terrain.go
util/mapeditor/main.go

Adds the missing indexes for terrain types.
Also shows the terrain type in the mapeditor:

Adds missing indexes to TerrainType

---

game/magic/game/game.go
game/magic/hero/hero.go
game/magic/maplib/map.go
game/magic/player/stack.go
game/magic/units/overworld.go
game/magic/units/stack-unit.go
lib/fraction/fraction.go
test/overworld/main.go

show remaining moves for the stack, and the movement icon.
not all movement icons are shown yet

Show movement

---

TODO
game/magic/armyview/view.go
game/magic/artifact/create-artifact.go
game/magic/artifact/item.go
game/magic/artifact/view.go
game/magic/cityview/build-screen.go
game/magic/combat/combat.go
game/magic/data/abilities.go
game/magic/data/enchantment.go
game/magic/game/game.go
game/magic/game/hero.go
game/magic/game/mercenaries.go
game/magic/game/merchant.go
game/magic/game/vault.go
game/magic/ui/ui.go
game/magic/unitview/ui.go
game/magic/unitview/unit.go
game/magic/util/graphics.go
test/artifact/main.go
test/glow/main.go
test/merchant/main.go
test/overworld/main.go
util/artifact-viewer/main.go

handle artifact abilities, and make the artifact glow when imbued with an ability

Artifact glow1

---

game/magic/maplib/map.go

set the minimap colors for the tiles, although the colors aren't great

update minimap colors for tiles

---

game/magic/city/city.go
game/magic/game/game.go
game/magic/game/surveyor.go
test/overworld/main.go

also allow the plane to be switched while in the surveyor

surveyor: show city name and resources

---

TODO
game/magic/artifact/create-artifact.go
game/magic/artifact/item.go
game/magic/game/cast.go
game/magic/game/game.go
game/magic/spellbook/data.go
test/artifact/main.go
test/overworld/main.go

Add the 'spell charges' option to creating artifacts.

artifact: add spell charge power in the creation ui

---

game/magic/cityview/build-screen.go
test/cityview/main.go

Don't let the building sprite overflow its box

cityview: clip building view

---

game/magic/game/game.go
game/magic/main.go
game/magic/maplib/map.go
test/overworld/main.go

map: create bonus tiles

---

game/magic/spellbook/spell.go

Adds help to spell book:
Works for casting spell book and when choosing a new spell to learn, not however when viewing the spell book via apprentice. It looks like this would need a bigger refactor to work?

Spell help

---

game/magic/game/cast.go
test/overworld/main.go

Add transmute spell similar to [Change Terrain](https://github.com/kazzmir/master-of-magic/pull/220)

spell: add transmute

---

game/magic/mirror/mirror.go
test/mirror/main.go

Add wizard name to the mirror.
Also show full hero title like in the original.

mirror: add wizard name

---

game/magic/terrain/map.go

fixes https://github.com/kazzmir/master-of-magic/issues/216
magic nodes can't be within 3 tiles of each other on the same continent

make sure magic nodes arent too close to each other

---

game/magic/armyview/view.go
game/magic/cityview/city-screen.go
game/magic/game/game.go
game/magic/hero/hero.go
game/magic/player/stack.go
game/magic/units/overworld.go
game/magic/units/stack-unit.go
test/overworld/main.go

Engineers become inactive while they are building a road. Multiple engineers building a road on the same tile build the road faster, and different terrain types take different amounts of total work to build a road section.

roads: engineers wait a few turns to build a road

---

game/magic/game/cast.go
game/magic/game/game.go

use a generic function to convert tile coordinates to screen pixel coordinates

cast: use tile to screen function

---

game/magic/data/data.go
game/magic/game/game.go
game/magic/ui/dialogs.go

settings: add button to change upscaling mode

---

TODO
game/magic/game/game.go
game/magic/game/hero.go
game/magic/hero/hero.go
game/magic/hero/hero_test.go
game/magic/mirror/mirror.go
game/magic/player/player.go
test/overworld/main.go

Hero progression

---

game/magic/combat/end-screen.go
game/magic/game/game.go
test/overworld/main.go

then go into the vault for each item the hero had

hero: redistribute items if a hero dies in combat

---

TODO
game/magic/game/game.go
game/magic/maplib/map.go
test/overworld/main.go

works similar to building roads where more priests purifies tiles faster

purify: implement unit purify ability

---

game/magic/game/game.go
game/magic/util/image-cache.go
test/overworld/main.go

autocrop wasn't working because img.SubImage(rect) doesn't account for the offset of the rect bounds, so sub.At(0,0) is really 0,0 in the parent

new building: fix image cropping

---

game/magic/data/enchantment.go
game/magic/game/game.go
game/magic/player/stack.go
test/overworld/main.go

implement terrain costs for movement, and some abilities like pathfinding

Pathfinding ability

---

lib/lbx/help.go
test/help/main.go

Tries to autocorrect name when getting help.

help: add autocorrection

---

game/magic/spellbook/data.go
test/overworld/main.go

spellbook: fix section and order by cast cost

---

game/magic/ai/enemy.go
game/magic/ai/raider.go
game/magic/game/cast.go
game/magic/game/game.go
game/magic/main.go
game/magic/maplib/map.go
game/magic/player/player.go
test/overworld/main.go
test/scale/main.go

create AI wizards when the game starts. issue random movement orders for units

game: add enemy ai wizards

---

game/magic/data/data.go
game/magic/game/game.go
game/magic/main.go
game/magic/terrain/map.go

```
$ ./magic -start
```
Jumps right into a game without having to go through the new game/new wizard screens

cli: use -start to instantly start a new game with a random wizard

---

game/magic/cityview/city-screen.go
test/cityview/main.go

city walls should always show up near the bottom of the city scape

city: hard code the position of city walls in the city scape

---

TODO
game/magic/ai/raider.go
game/magic/combat/combat-screen.go
game/magic/combat/end-screen.go
game/magic/combat/model.go
game/magic/game/game.go
game/magic/hero/hero.go
game/magic/player/stack.go
game/magic/units/overworld.go
game/magic/units/stack-unit.go
game/magic/units/unit.go
test/overworld/main.go

Improves fleeing from combat.
I thought this would only be a small change but it turned out to be much bigger 😬
Changes:
- Units have a chance to die while fleeing
- normal units have a chance of 50%, heroes of 25% ([wiki](https://masterofmagic.fandom.com/wiki/Encounter_Zone))
- units dying while fleeing during combat count as killed units and will lead to experience (not 100% sure this makes sense)
- Fled units are relocated on the map
- Movement costs/remaining movement is ignored (I think this is how it's implemented in the original game, but not 100% sure)
- Attackers are reset to their last positions
- Defenders try to find an empty location in a radius of one tile which has no encounters/enemy cities/enemy stacks (I think this more or less how it was in the original if I remember …

combat: improve fleeing

---

game/magic/city/city.go
game/magic/cityview/city-screen.go
game/magic/data/enchantment.go
game/magic/game/game.go
test/overworld/main.go

population growth is negative, and required food is shown in grey icons

city: handle cases where not enough food is produced

---

TODO
game/magic/artifact/create-artifact.go
game/magic/cityview/city-screen.go
game/magic/data/enchantment.go
game/magic/game/cast.go
game/magic/game/game.go
game/magic/game/vault.go
game/magic/magicview/view.go
game/magic/player/player.go
game/magic/spellbook/spell.go
game/magic/ui/dialogs.go
game/magic/unitview/ui.go
test/magicview/main.go
test/overworld/main.go

game: implement global enchantment casting and handling

---

game/magic/cityview/city-screen.go
game/magic/magicview/view.go
test/cityview/main.go

Shows help on right click for global and city enchantments. Like in the original game, only shows the help about global enchantments if no global enchantment are in place.

enchantment: show help

---

game/magic/city/city.go
game/magic/cityview/city-screen.go
game/magic/data/enchantment.go
game/magic/game/cast.go
test/cityview/main.go
test/overworld/main.go

I'm not 100% sure about the bonus calculation, I went with ["Gold is increased by 100%, like a Merchants' Guild does"](https://masterofmagic.fandom.com/wiki/Prosperity).

Cast prosperity

---

game/magic/city/city.go
game/magic/cityview/city-screen.go
game/magic/data/enchantment.go
game/magic/game/cast.go
test/cityview/main.go
test/overworld/main.go

Inspirations gives [a bonus equal to the production of the farmers and workers](https://masterofmagic.fandom.com/wiki/Inspirations)

cast: add inspirations

---

game/magic/terrain/map.go
game/magic/terrain/map_test.go

add some test cases for finding continents, which fixed another small bug

terrain: clean up find continent code and add tests

---

game/magic/ai/enemy.go
game/magic/ai/raider.go
game/magic/banish/banish.go
game/magic/city/city.go
game/magic/combat/end-screen.go
game/magic/game/game.go
game/magic/player/player.go
game/magic/ui/dialogs.go
game/magic/ui/ui.go
game/magic/units/unit.go
test/banish/main.go
test/overworld/main.go

defeating a city gives the player a chance to occupy or raze the city. If the city contained the wizard's fortress, then that wizard is banished.

game: raze/occupy a defeated city

---

game/magic/game/game.go

Fixes fame from capture or raze city not getting added to players' fame.

game: fix capture/raze fame

---

game/magic/game/game.go
game/magic/music/midi_js.go
game/magic/music/music.go
lib/midi/drivers/reader.go
lib/midi/drivers/testdrv/driver_test.go
lib/midi/drivers/webmididrv/out.go
lib/midi/example_test.go

also fix a bug in the midi driver output for browsers

songs: add constants for most song names

---

game/magic/cityview/city-screen.go
game/magic/game/cast.go
test/overworld/main.go

Adds the famine spell (enchantment was already implemented).
Also hides enemy units in simplified city view due to fog of war.

cast: add famine

---

game/magic/city/city.go
game/magic/city/city_test.go

Base food level is [halved](https://masterofmagic.fandom.com/wiki/Maximum_Population#Famine) if famine is active.

city: add famine effect on base food level

---

game/magic/cityview/city-screen.go
game/magic/ui/ui.go

show a 'more' button that can be used to scroll through the pages of resource usage

resource icon page: show more button

---

game/magic/building/building.go
game/magic/city/city.go
game/magic/city/city_test.go
game/magic/cityview/city-screen.go
game/magic/cityview/enchantment.go
game/magic/data/enchantment.go
game/magic/game/cast.go
game/magic/game/game.go
test/city-enchantment/main.go
test/overworld/main.go

Adds the [Dark Rituals](https://masterofmagic.fandom.com/wiki/Dark_Rituals) spell.
Effects:
- doubles power from religious buildings
- increases unrest by 1
- reduces population growth by 25%
Changes in city screen:
- remove buildings / slots when disabling enchantments
- report power from dark rituals
Als oupdates / adds some fixmes for later.

cast: dark rituals

---

game/magic/city/city.go
game/magic/city/city_test.go
game/magic/game/cast.go
test/overworld/main.go

Adds [stream of life](https://masterofmagic.fandom.com/wiki/Stream_of_Life):
- Reduces unrest to 0 (!)
- Doubles population growth in cities
- increases growth chance by 10% in outposts

cast: add stream of life

---

game/magic/game/game.go
game/magic/maplib/map.go
test/overworld/main.go

https://masterofmagic.fandom.com/wiki/Encounter_Zone#Towers_of_Wizardry
after defeating a plane tower, the tower becomes open and units can switch planes while standing on top of it
closes https://github.com/kazzmir/master-of-magic/issues/217

game: implement plane towers

---

game/magic/data/enchantment.go
game/magic/game/cast.go
game/magic/game/game.go
game/magic/player/player.go
game/magic/unitview/ui.go
test/overworld/main.go

Cast a persistent enchantment on a unit from the overland

units: implement unit persistent enchantments

---

game/magic/console/console.go
game/magic/data/enchantment.go
game/magic/game/cast.go
game/magic/unitview/ui.go
test/overworld/main.go
test/scale/main.go

Fill out rest of the unit enchantment spells.
This also adds 'cast' as a command to the in-game console.

units: implement more enchantments

---

game/magic/artifact/create-artifact.go
game/magic/artifact/item.go
game/magic/combat/combat-screen.go
game/magic/combat/model.go
game/magic/data/abilities.go
game/magic/data/enchantment.go
game/magic/game/game.go
game/magic/hero/hero.go
game/magic/player/player.go
game/magic/player/stack.go
game/magic/units/overworld.go
game/magic/units/stack-unit.go
test/merchant/main.go
test/overworld/main.go

Handle plane shifting for towns with an astral gate as well as the plane shift ability. Also separate item powers from regular abilities, where item powers confer abilities/unit enchantments

game: plane shift if city has astral gate

---

game/magic/game/game.go
game/magic/game/hero.go
test/hire-hero/main.go

hero: get name of hero from user

---

game/magic/armyview/view.go
test/overworld/main.go

Hovering over a hero in the army view should highlight them, and clicking on a hero picture should set them to be the selected stack

army view: implement ux for hero

---

game/magic/armyview/view.go
game/magic/artifact/create-artifact.go
game/magic/cityview/build-screen.go
game/magic/cityview/city-screen.go
game/magic/game/game.go
game/magic/game/hero.go
game/magic/game/mercenaries.go
game/magic/game/vault.go
game/magic/hero/hero.go
game/magic/magicview/view.go
game/magic/spellbook/spell.go
game/magic/ui/dialogs.go
game/magic/ui/ui.go
game/magic/unitview/ui.go
game/magic/unitview/unit.go
test/abilities/main.go
test/hire-hero/main.go
test/hire-mercenaries/main.go

Be able to click on items/abilities in the unit view

unitview: make ui elements for abilities/items to interact with

---

game/magic/cityview/build-screen.go
game/magic/cityview/city-screen.go
game/magic/fonts/fonts.go
game/magic/game/game.go
game/magic/game/vault.go
game/magic/magicview/view.go
game/magic/setup/new-wizard.go
game/magic/spellbook/spell.go
game/magic/ui/dialogs.go
game/magic/ui/ui.go
game/magic/unitview/unit.go

right clicking on an item in the unitview should do something. for an artifact the item popup will display the items attributes. for a unit ability, the help box will show up explaining that ability.
This also adds a new `fonts` module that we can use to centralize font creation.

unitview: right click on abilities and items to show help or more info

---

game/magic/artifact/view.go
game/magic/fonts/fonts.go
game/magic/game/merchant.go
game/magic/game/vault.go
game/magic/unitview/unit.go

fix the font used for powers of the item
closes https://github.com/kazzmir/master-of-magic/issues/331

artifact: use vault font for item popup display

---

game/magic/ui/dialogs.go
game/magic/ui/ui.go

use an interface that abstracts away group vs ui

ui: use generic container interface

---

game/magic/armyview/view.go
game/magic/cityview/build-screen.go
game/magic/cityview/city-screen.go
game/magic/cityview/enchantment.go
game/magic/fonts/fonts.go

Move armyview and cityview fonts

fonts: continue moving font creation to the fonts module

---

game/magic/game/game.go
game/magic/hero/names.go
game/magic/player/player.go
game/magic/player/player_test.go
test/combat/main.go
test/magicview/main.go
util/combat-simulator/main.go
util/lbxdump/main.go

```
$ go run ./util/lbxdump/ magic-data/NAMES.LBX 
Opening magic-data/NAMES.LBX as an lbx file
Number of files: 1
2025/02/17 22:16:57.346251 main.go:70: Choice 1: map[0:Azrael 1:Dreadwing 2:Abdul Shaza 3:Tabatha 4:Kolimak 5:Nymos 6:Rockfist 7:Aleron 8:Jester 9:Sir Henry 10:Dolgin 11:Ulrik 12:Tholin 13:Diana 14:Charles 15:Delian 16:Redblade 17:Wolfar 18:Salkirg 19:Graydon 20:Quai Chang 21:Grofzinar 22:Lauren 23:Victoria 24:Xoara 25:Cassius 26:Stalkaor 27:Gwendolyn 28:Jesrael 29:Omi 30:Shardis 31:Artemis 32:Shadow 33:Altahza 34:Orlo]
2025/02/17 22:16:57.346312 main.go:70: Choice 2: map[0:Lawrence 1:Drakus 2:Fazeel 3:Karlota 4:Harlak 5:Morphis 6:Yaga 7:Destin 8:Marco 9:Stephan 10:Grendel 11:Narlok 12:Greenleaf 13:Lana 14:Fairley 15:Furius 16:Marek 17:Angus 18:Wyn 19:Aquilon 20:Tonaga …
```

hero: read default hero names from names.lbx

---

DEVELOPMENT.md

Add a description of development guidelines for the project

development guidelines

---

game/magic/city/city.go
game/magic/game/game.go
game/magic/game/game_test.go
game/magic/player/player.go

make common function for changing ownership of a city

game: use common function for changing city ownership

---

game/magic/cityview/build-screen.go
game/magic/cityview/city-screen.go

closes https://github.com/kazzmir/master-of-magic/issues/344

cityview: use unique sprite for city walls

---

game/magic/combat/combat-screen.go
game/magic/combat/end-screen.go
game/magic/combat/model.go
game/magic/game/game.go
game/magic/player/player.go
lib/set/set.go
test/overworld/main.go

implement town collateral damage after a battle.
https://masterofmagic.fandom.com/wiki/Town#Collateral_Damage

start town collateral damage

---

game/magic/fonts/fonts.go
game/magic/game/cast.go
game/magic/game/events.go
game/magic/game/game.go
game/magic/game/hero.go
game/magic/game/mercenaries.go
game/magic/game/merchant.go
game/magic/game/surveyor.go
test/overworld/main.go

move most of the font loading code from game/ into fonts/

fonts: refactor font creation

---

game/magic/game/cast.go
game/magic/music/music.go
test/overworld/main.go

Play a specific song for each global enchantment that is cast

global enchantments: play music

---

game/magic/game/cast.go
game/magic/game/game.go
game/magic/maplib/map.go
game/magic/player/player.go
test/overworld/main.go

mapObject.GetSquareAreaAround() ended up being unused, but it seems helpful enoough so I left it there.

Implement Awareness spell.

---

game/magic/city/city.go
game/magic/game/cast.go
game/magic/game/game.go
game/magic/hero/hero.go
game/magic/units/overworld.go
game/magic/units/stack-unit.go
game/magic/unitview/ui.go
game/magic/unitview/unit.go
test/overworld/main.go

Adds [Altar of Battle](https://masterofmagic.fandom.com/wiki/Altar_of_Battle) and [Crusade](https://masterofmagic.fandom.com/wiki/Crusade) spells, and [Heroism](https://masterofmagic.fandom.com/wiki/Heroism)
| City/Unit   | Start Experience | Level   | Crusade or Warlord | Crusade and Warlord |
| --------------- | ---------------- | ------- | ------------------ | ------------------- |
| None            | 0                | Recruit | Regular            | Veteran             |
| Fighter's Guild | 20               | Regular | Veteran            | Elite               |
| War College     | 61               | Veteran | Elite              | Ultra-Elite         |
| Altar of Battle/Heroism | 120              | Elite   | Ultra-Elite        | Champion            |

cast: altar of battle and crusade

---

game/magic/data/enchantment.go
game/magic/fonts/fonts.go
game/magic/game/cast.go
game/magic/game/game.go
game/magic/spellbook/data.go
game/magic/spellbook/spell.go
game/magic/units/overworld.go
test/cast-spell/main.go
test/overworld/main.go

https://masterofmagic.fandom.com/wiki/Disenchant_Area
also add an 'additional power' ui element for some spells
the additional power goes into spell.OverrideCost

cast: disenchant area

---

game/magic/armyview/view.go
game/magic/artifact/view.go
game/magic/combat/combat.go
game/magic/game/game.go
game/magic/unitview/ui.go
game/magic/util/graphics.go
test/shader/main.go

Apply scaling to the outline edge shader
before:
after:

graphics: apply scaling to the outline shader

---

game/magic/data/enchantment.go
game/magic/game/cast.go

The sound index is not yet known, but the mechanics of plane shifting on a city with astral gate is already implemented

cast: astral gate town enchantment

---

game/magic/city/city.go
game/magic/city/city_test.go
game/magic/game/cast.go
game/magic/game/game.go
game/magic/player/player.go
test/overworld/main.go

Adds [Just Cause](https://masterofmagic.fandom.com/wiki/Just_Cause):
- Adds +10 to basic fame 
- Adds +1 pacification
This PR also ensures that basic fame will never go below 10, so minimum fame will be 10 with Just Cause.

cast: add just cause

---

game/magic/combat/combat-screen.go
game/magic/combat/model.go
game/magic/data/enchantment.go
test/combat/main.go

show an animation when a combat enchantment is cast, and show the enchantment icon in the hud

combat: show animation for casting enchantments

---

game/magic/artifact/create-artifact.go
game/magic/city/city.go
game/magic/cityview/city-screen.go
game/magic/units/unit.go
util/lbxdump/main.go

Removes obsolete todos/fixmes and fixes two small bugs:
- Stag Beetles requires stables (Klackons cannot build fantastic stables)
- Only show building which actually can be built by this race in "Allows"

Small fixes

---

game/magic/city/city.go
game/magic/data/data.go
game/magic/game/cast.go
game/magic/game/game.go
game/magic/game/hero.go
game/magic/maplib/map.go
game/magic/player/player.go
game/magic/terrain/terrain.go
test/overworld/main.go

Adds [Armageddon](https://masterofmagic.fandom.com/wiki/Armageddon) and [Great Wasting](https://masterofmagic.fandom.com/wiki/Great_Wasting).
Contains some small other fixes:
- Moves consecration purifiaction code from game to city's ` DoNextTurn`
- Fixes y position check in location finder
- Fixes UI being stuck after rejecting a hero

cast: Add Armageddon and Great Wasting

---

game/magic/combat/combat-screen.go
game/magic/combat/combat_test.go
game/magic/combat/model.go
game/magic/units/unit.go
test/combat/main.go

implement mechanics for more combat enchantments

combat: implement most of the other enchantments

---

game/magic/city/city.go
game/magic/city/city_test.go
game/magic/combat/combat-screen.go
game/magic/combat/combat_test.go
game/magic/combat/model.go
game/magic/game/game.go
game/magic/game/game_test.go
lib/fraction/fraction.go
test/combat/main.go
util/combat-simulator/main.go

also implement mana cost as spell cost * range: https://masterofmagic.fandom.com/wiki/Casting_Cost#Combat_Spellcasting

combat: show skill/mana/range for attacker

---

game/magic/game/game.go
game/magic/shaders/drop-shadow.kage
game/magic/shaders/outline.kage
game/magic/shaders/shaders.go
game/magic/shaders/shaders_test.go
game/magic/util/image-cache.go
lib/font/font.go
test/font/main.go

font: draw outline around glyphs

---

game/magic/cityview/build-screen.go
game/magic/cityview/city-screen.go
game/magic/combat/combat-screen.go
game/magic/combat/end-screen.go
game/magic/diplomacy/diplomacy.go
game/magic/game/game.go
game/magic/game/merchant.go
game/magic/game/surveyor.go
game/magic/mirror/mirror.go
game/magic/spellbook/spell.go
game/magic/ui/dialogs.go
lib/font/font.go
test/page-turn/main.go

font: apply shadows when wrapping text

---

lib/font/font.go
test/font/main.go

font: let shadow color be a parameter in the font options

---

game/magic/audio/cache.go
game/magic/combat/combat-screen.go

Combat is slightly laggy in wasm because loading sounds is slow. Use a cache to speed things up

audio: cache sounds

---

game/magic/cityview/build-screen.go
game/magic/cityview/city-screen.go
game/magic/combat/combat-screen.go
game/magic/combat/combat.go
game/magic/combat/model.go
game/magic/combat/unit-view.go
game/magic/data/enchantment.go
game/magic/game/hero.go
game/magic/game/mercenaries.go
game/magic/hero/hero.go
game/magic/mirror/mirror.go
game/magic/units/overworld.go
game/magic/units/stack-unit.go
game/magic/unitview/combat.go
game/magic/unitview/ui.go
game/magic/unitview/unit.go
test/combat-info/main.go
test/combat/main.go

right click to bring up the unit info popup during combat.
not sure if I will keep this, its just an experiment

combat: show unit info on right click

---

game/magic/fonts/fonts.go
game/magic/game/cast-select-wizard.go
game/magic/game/cast.go
game/magic/game/select_wizard_ui.go
game/magic/player/player.go
game/magic/spellbook/data.go
test/overworld/main.go
util/lbxdump/main.go

cast: spell blast

---

game/magic/game/cast.go

cast: fix copy paste errors

---

lib/font/read.go
util/fonteditor/main.go

```
$ go run ./util/fonteditor
```

font editor: add utility to develop font palettes

---

game/magic/game/game.go
game/magic/magicview/view.go
game/magic/player/player.go
test/overworld/main.go

Heroes that are currently at the fortress city add their caster ability to the casting skill of the player

player: include hero caster ability

---

util/mapeditor/main.go

Allow setting other terrain than grass and autoresolve the terrain just set.

map-editor: allow setting other terrain

---

util/mapeditor/main.go

@kazzmir what do you think about allowing to load a map from an existing savegame?

mapeditor: allow loading from savegame

---

game/magic/game/cast.go
game/magic/game/game.go
game/magic/hero/hero.go
game/magic/summon/summon.go
test/summon/main.go

Female heroes are known ahead of time

summon: pass female flag into summon hero

---

game/magic/combat/combat-screen.go
game/magic/combat/model.go
game/magic/data/enchantment.go
game/magic/game/game.go
test/combat/main.go
util/combat-simulator/main.go

combat: implement web spell

---

game/magic/combat/combat_test.go
game/magic/combat/model.go

https://masterofmagic.fandom.com/wiki/Counter_Attack#Temporary_To_Hit_Penalty

combat: implement counter-attack tohit penalty

---

game/magic/data/data.go
game/magic/load/convert.go
game/magic/maplib/map.go
util/mapeditor/main.go

Adds terrain specials and encounters to the mapeditor (generate/load/draw).
I also started the conversion part, not sure about the naming and package layout.

mapeditor: add specials and encounters

---

game/magic/combat/combat-screen.go
game/magic/combat/model.go
game/magic/combat/spell_test.go
game/magic/shaders/edge-glow.kage
game/magic/util/graphics.go
test/combat/main.go

combat: implement warp creature

---

util/combat-simulator/server/go.mod
util/combat-simulator/server/go.sum

fixes https://github.com/kazzmir/master-of-magic/security/dependabot/3

combat simulator server: update dependencies

---

game/magic/maplib/map.go
game/magic/terrain/map.go
util/mapeditor/main.go

Before:
```
2025/03/13 15:58:08 Generated 100x200 Arcanus map in 53.391247ms
2025/03/13 15:58:08 Generated 100x200 Arcanus map in 54.024643ms
2025/03/13 15:58:08 Generated 100x200 Arcanus map in 56.269528ms
```
After:
```
2025/03/13 15:57:53 Generated 100x200 Arcanus map in 44.805507ms
2025/03/13 15:57:53 Generated 100x200 Arcanus map in 38.5493ms
2025/03/13 15:57:54 Generated 100x200 Arcanus map in 41.392034ms
```

map: optimize memory allocation when building the map

---

game/magic/combat/combat-screen.go
game/magic/combat/model.go
game/magic/combat/spell_test.go
test/combat/main.go

holy weapon, holy armor, and invulnerability
also implement weapon immunity and negating it

combat: implement more unit enchantment spells

---

game/magic/combat/combat-screen.go
game/magic/combat/model.go
game/magic/combat/spell_test.go
game/magic/combat/unit-view.go
game/magic/spellbook/spell.go
game/magic/units/overworld.go
game/magic/units/stack-unit.go
game/magic/unitview/ui.go
game/magic/unitview/unit.go
test/combat-info/main.go
test/combat/main.go
util/combat-simulator/main.go

implement the rest of the life and nature unit spells, and also flight

combat: implement more unit enchantments

---

game/magic/combat/combat-screen.go
game/magic/combat/combat_test.go
game/magic/combat/model.go
game/magic/combat/spell_test.go
game/magic/hero/hero.go
game/magic/units/overworld.go
game/magic/units/stack-unit.go
game/magic/unitview/combat.go
game/magic/unitview/ui.go
game/magic/unitview/unit.go
test/combat/main.go

Invisible units rendered in combat:

combat: haste, guardian wind, and invisibility

---

game/magic/combat/combat-screen.go
game/magic/combat/combat_test.go
game/magic/combat/model.go
game/magic/combat/spell_test.go
game/magic/units/overworld.go
test/combat/main.go

* magic immunity
* resist magic
* spell lock
* eldritch weapon
* flame blade
* immolation
fix some bugs regarding invisibility

combat: finish sorcery and chaos unit enchantments

---

game/magic/combat/combat-screen.go
game/magic/combat/model.go
game/magic/combat/spell_test.go
game/magic/hero/hero.go
game/magic/units/overworld.go
test/combat/main.go

* bersersk
* cloak of fear
* wraith form

combat: implement death enchantments

---

game/magic/combat/combat-screen.go
game/magic/combat/model.go
game/magic/game/game.go
game/magic/maplib/map.go
game/magic/maplib/map_test.go
game/magic/maplib/node.go
test/combat-info/main.go
test/combat/main.go
test/overworld/main.go
util/combat-simulator/main.go

nodes dispel magic from other realms, and fantastic creatures from the same realm as the magic node get bonuses to melee/defense/resistance

combat: node aura mechanics

---

game/magic/game/cast.go
game/magic/game/game.go
game/magic/player/stack.go
test/overworld/main.go

Units can teleport between two friendly cities that both have earth gate in them.

cast: earth gate

---

game/magic/combat/combat-screen.go
game/magic/combat/model.go
game/magic/game/cast.go
game/magic/game/damage.go
game/magic/game/damage_test.go
game/magic/game/game.go
game/magic/hero/hero.go
game/magic/units/overworld.go
game/magic/unitview/ui.go
game/magic/unitview/unit.go
test/overworld/main.go

re-use the combat functions for applying damage because chaos rift does 8 magic armor piercing damage

cast: chaos rift

---

game/magic/combat/model.go

Use a more generic cleanup function to unset the enchantment provider on units

combat: invoke cleanup functions

---

game/magic/spellbook/spell.go
test/cast-spell/main.go

add buttons to filter spells by their magic realm

cast ui: add buttons to filter by magic realm

---

game/magic/game/cast.go
game/magic/spellbook/spell.go
game/magic/ui/ui.go
test/overworld/main.go

cast: disjunction and disjunction true

---

game/magic/fonts/fonts.go
game/magic/game/game.go
game/magic/mastery/mastery.go
game/magic/util/image-cache.go
lib/font/font.go
lib/lbx/lbx.go
test/hire-hero/main.go
test/mastery/main.go
test/overworld/main.go
util/lbxviewer/main.go

show animation for spell of mastery when selecting the spell to cast, and when it is finally cast

cast: spell mastery

---

game/magic/armyview/view.go
game/magic/game/game.go
test/overworld/main.go

these buttons let you filter the armies that are shown based on their plane

army view: add buttons to filter by plane

---

game/magic/combat/combat-screen.go
game/magic/combat/model.go
game/magic/game/cast.go
lib/font/font.go
test/combat/main.go

combat: show info ui

---

game/magic/fonts/fonts.go
game/magic/game/cast.go
game/magic/game/game.go
game/magic/ui/ui.go
test/overworld/main.go

when a spell is dispelled due to tranquility, show this ui

game: show fizzle animation for tranquility

---

game/magic/game/vault.go
game/magic/mouse/mouse.go

The mouse should render artifacts with the glowing edge in the vault the same way the artifacts are rendered normally.

vault: use a function to render the mouse for the vault items

---

game/magic/fonts/fonts.go
game/magic/mainview/view.go

main screen: show credits

---

game/magic/fonts/fonts.go
game/magic/game/cast-select-wizard.go
game/magic/game/cast.go
game/magic/game/game.go
game/magic/mainview/view.go
game/magic/mastery/mastery.go
game/magic/setup/new-wizard.go
game/magic/unitview/ui.go
util/font-list/main.go

Create a UI for viewing all available fonts

fonts: add font list utility, and define each font with a name

---

game/magic/cartographer/cartographer.go
game/magic/fonts/fonts.go
game/magic/game/game.go
test/cartographer/main.go

Implement the cartographer menu

cartographer: implement ui

---

game/magic/game/game.go
game/magic/help/help.go
game/magic/main.go
game/magic/mainview/view.go

main menu: right click on main menu shows some help items

---

lib/lbx/cache.go
util/lbxviewer/main.go

Automatically load data from the cache. Also support vi keys for navigation

lbxviewer: autoload data

---

game/magic/game/game.go

The chancellor advisor shows all events that occurred during the current turn.

chancellor advisor

---

game/magic/game/game.go
game/magic/player/player.go
test/overworld/main.go

game: implement astrologer view, and player overall power

---

game/magic/combat/combat-screen.go
game/magic/data/data.go
game/magic/fonts/fonts.go
game/magic/game/game.go
game/magic/player/player.go
test/overworld/main.go

historian: implement view

---

game/magic/game/game.go

N for next turn, F1-F9 for advisor windows

game: handle hotkeys for advisor windows

---

game/magic/combat/combat-screen.go
game/magic/game/game.go
game/magic/game/learn-spell.go
game/magic/player/player.go
game/magic/spellbook/spell.go
test/cast-spell/main.go

fixes https://github.com/kazzmir/master-of-magic/issues/350
The apprentice spell book opens to the currently researching spell, or just to the first page of the book if there are no spells being researched (because the wizard has researched them all).
The combat spell book will open to the last page that was shown.

spellbook: track which spell book page the user had opened

---

game/magic/combat/combat-screen.go
game/magic/combat/combat_test.go
game/magic/combat/model.go
game/magic/game/game.go
game/magic/units/experience.go
util/combat-simulator/main.go

show boulder icon for slingers/steam cannon. also show experience badge and ammo/mp left

combat: show ranged attack properties in info box

---

game/magic/cityview/city-screen.go
game/magic/game/game.go

double click on the city name to show an input box that will change the name

cityview: double click name to change it

---

game/arena/main.go

arena: show unit stats in buy list

---

game/arena/cost.go
game/arena/main.go
game/magic/combat/combat-screen.go
game/magic/combat/model.go
game/magic/combat/spell_test.go
test/combat/main.go

AI controlled armies will cast spells by re-using the existing InvokeSpell logic that can target the proper units. For some spells the AI will use extra logic to decide whether to cast, such as casting healing on a unit that has taken damage.

arena: enemy can use magic

---

game/arena/cost.go
game/arena/main.go
game/magic/combat/model.go

The enemy's army may have upgraded melee weapons as well

arena: enemy can upgrade melee weapon

---

game/arena/main.go
game/magic/combat/combat-screen.go

combat: show highlight around unit by pressing tab

---

game/arena/main.go

arena: render the books that the player has for spells

---

game/arena/cost.go
game/arena/main.go
game/magic/combat/model.go

difficulties change the amount of reward, and how much budget the enemy gets when setting up their army

arena: set difficulty level in new game ui

---

game/arena/main.go
game/arena/player/player.go
game/magic/units/unit.go

arena: sell units

---

game/arena/main.go

arena: show mana cast cost for spells

---

game/magic/combat/combat-screen.go
game/magic/combat/model.go
test/combat/main.go

combat: show damage indicators
